### PR TITLE
Change http asset loading to https

### PR DESCRIPTION
**Pull request by ghost**
All my browsers were failing to render the page correctly. It seems that because the site is loaded over https, the browsers block assets loaded over http. I updated the ones I could find.

### CODE REVIEW

**Comment by leerho** [comment]
For the time being, please load the site using http://.  There are over 5200 references to http:// in the site so I'll have to look at this later.  I will keep this PR open pending further study.

**Comment by ghost** [comment]
Sure thing. The API docs appear to have no issues, just the landing page and overviews.

**Comment by leerho** [comment]
I did a more exhaustive search and found all of them ( I hope! ).  Thank you for uncovering this.

**Comment by ghost** [comment]
No problem, thanks for putting this well documented package online!

**Pull request closed without merging**
