### PR TITLE
Attempt to replace 3rd party links with locally hosted versions

### PR DESCRIPTION
**Pull request by jmalkin**
Not sure if this will work since I dunno how to test this locally. I installed jekyll but it seems to need a lot of additional dependencies.

### CODE REVIEW

**Comment by jmalkin** [comment]
Not sure what to do about this CodeQL issue in code we've been using from a 3rd party.

**Comment by dave2wave** [comment]
> Not sure what to do about this CodeQL issue in code we've been using from a 3rd party.

I would continue with this PR and make a new issue to investigate how to focus in on a not minimized version of the js dependency.

**Comment by jmalkin** [comment]
Ok, gonna try merging this. It might break the site and need to be reverted.

**Comment by jmalkin** [comment]
I don't see anything obviously broken at least? I'll leave the branch around for a bit in case anyone notices major problems and we need to revert but I am optimistic that this was successful.

**Pull request merged**
