### PR TITLE
Fixed ThetaSketchJava example; incorrect method call.

### PR DESCRIPTION
**Pull request by priyamtejaswin**
Hello,
I was trying the DataSketches library, starting with the ThetaSketches example for Java core.
I believe there are some typos in the example.
The example called `update(<sketch>)` method for updating the union and intersection sketches.
This is not supported by the class. Fixed/replaced with `union` and `intersection` respectively.

This is an excellent library btw! An amazing effort! Thanks to all the devs involved!

### CODE REVIEW

**Comment by priyamtejaswin** [comment]
On a side note, a new user would have to add some boilerplate code for the example.
Java won't let me use a lot of the IO calls (`FileOutputStream, FileInputStream`, etc) without adding `try/catch` blocks.
I could raise a PR with all of that if needed.

**Review by leerho — APPROVED** [review]

**Comment by leerho** [comment]
Thank you!

**Comment by leerho** [comment]
Could you give us some examples of how you would use the IO calls?

**Comment by leerho** [comment]
Are you talking about the example code?  If so, the example code is simplified by design to eliminate a lot of boilerplate code.

**Comment by priyamtejaswin** [comment]
Hi Lee,

> Could you give us some examples of how you would use the IO calls?

Sure. My IDE was troubling me to handle IO exceptions. So for `FileOutputStream`, instead of 
```java
UpdateSketch sketch1 = UpdateSketch.builder().build();
for (int key = 0; key < 100000; key++) sketch1.update(key);
FileOutputStream out1 = new FileOutputStream("/path/ThetaSketch1.bin", false);
out1.write(sketch1.compact().toByteArray());
out1.close();
```
I had to rewrite it as 
```java
        UpdateSketch sketch1 = UpdateSketch.builder().build();
        for (int key = 0; key < 100000; key++) sketch1.update(key);
        try {
            FileOutputStream out1 = new FileOutputStream("/path/ThetaSketch1.bin", false);
            try {
                out1.write(sketch1.compact().toByteArray());
                out1.close();
            } catch (IOException ioe) {
                System.out.println(ioe.getMessage());
            }
        } catch (FileNotFoundException fnfe) {
            System.out.println(fnfe.getMessage());
        }
```
It's possible this is a IDE specific thing (I develop and test using Intellij).

> Are you talking about the example code? If so, the example code is simplified by design to eliminate a lot of boilerplate code.

Yes. I was talking about the example code specifically.
Ah yes I guessed the example was simplified to keep the boilerplate out of the way.
I think it suffices.

**Comment by priyamtejaswin** [comment]
> Sure. My IDE was troubling me to handle IO exceptions.

When I say "troubling" I meant it would not let me build and run unless I account for the IO exception handling.

**Comment by leerho** [comment]
Of course.  But the IOExceptions are entirely due to your use of FileOutputStream and nothing to do with the sketch.

**Pull request merged**
