### PR TITLE
updated releases

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**
Updated using the createDownloadsInclude.sh script

### CODE REVIEW

**Review by leerho — CHANGES_REQUESTED** [review]
According to Apache ([Release Policy](https://www.apache.org/legal/release-policy.html)), the Apache [downloads](https://downloads.apache.org) site, which is populated from 
[dist/release](https://dist.apache.org/repos/dist/release/) should only contain the latest release as earlier releases are automatically available from the Apache [archive](https://archive.apache.org/dist/).

Thus, the earlier releases of CPP and PostgreSQL should be removed from dist/release before running the _createDownloadsInclude.sh_ script.

**Review by leerho — CHANGES_REQUESTED** [review]
Please follow instructions from previous review:
"the earlier releases of CPP and PostgreSQL should be removed from dist/release before running the createDownloadsInclude.sh script."

**Comment by AlexanderSaydakov** [comment]
done

**Review by leerho — APPROVED** [review]
thank you!

**Pull request merged**
